export const generateHtmlForModel = (modelDataUrl: string, modelName: string): string => {
  // Sanitize modelName to prevent HTML injection
  const sanitizedModelName = modelName.replace(/</g, "&lt;").replace(/>/g, "&gt;");

  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>3D Viewer: ${sanitizedModelName}</title>
    <!-- Imports the model-viewer web component -->
    <script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></script>
    <style>
      html, body {
        height: 100%;
        width: 100%;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #111827; /* bg-gray-900 */
        font-family: sans-serif;
      }
      model-viewer {
        width: 100%;
        height: 100%;
        --progress-bar-color: #2563eb; /* blue-600 */
        --progress-mask: #374151; /* gray-700 */
      }
      .credit {
        position: fixed;
        bottom: 10px;
        right: 10px;
        font-size: 12px;
        color: #6b7280; /* text-gray-500 */
        pointer-events: none;
      }
    </style>
</head>
<body>
  <!--
    Auto-generated by Interactive 3D Viewer
  -->
  <model-viewer
      src="${modelDataUrl}"
      alt="A 3D model of ${sanitizedModelName}"
      ar
      ar-modes="webxr scene-viewer quick-look"
      camera-controls
      auto-rotate
      enable-pan
      shadow-intensity="1"
      environment-image="neutral"
      exposure="1">
  </model-viewer>
  <div class="credit">Generated by Interactive 3D Viewer</div>
</body>
</html>`;
};
